name: Bug Report
description: Issue with the server, unexpected behaviour
title: "[Bug]: "
labels: ["need review"]
assignees:
  - wdp-2010
type: Bug
projects: ["WDP-Server/2"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!  
        Please try to provide as much information as possible.

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "Example: The game crashes when I look at a specific chunk border..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior (be as specific as possible).
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: markdown
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Videos
      description: |
        If applicable, add screenshots or short video clips to help explain your problem.
        You can drag & drop or paste them here.
      placeholder: "Drag images/videos here or use the upload button ↑"
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: OS
      description: Your operating system
      placeholder: Windows 11 / macOS Ventura / Linux (Ubuntu 24.04) / etc.
    validations:
      required: false

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Version
      placeholder: 1.20.1 / 1.21 / etc.
    validations:
      required: true

  - type: dropdown
    id: modloader
    attributes:
      label: Mod Loader
      options:
        - Vanilla
        - Fabric
        - Quilt
        - Forge
        - NeoForge
        - Lunar Client
        - Other (please specify in additional context)
      default: 0
    validations:
      required: true

  - type: textarea
    id: mods-list
    attributes:
      label: Mods / Modpack
      description: List the most important / relevant mods (or full modpack name + version)
      placeholder: |
        - Distant Horizons 2.1.0-a
        - Sodium 0.5.8
        - Iris 1.7.0
        - Lithium 0.12.1
        - or: Fabulously Optimized 5.2.0
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Latest.log or crash-report (if any)
      description: |
        Please paste the **latest.log** or crash-report here (use https://mclo.gs/ or pastebin if very long).
        This helps enormously when diagnosing crashes and errors.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here (shaders used, resource packs, JVM args, etc.).
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By submitting this issue you agree to follow our community guidelines.
      options:
        - label: I have made sure this issue has **not** already been reported
          required: true
        - label: I have included the **latest.log** / crash-report (or explained why not)
          required: false
